apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: packersmovers
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: packersmovers
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
